### ISSUE TITLE
L5.6 incompatibility

### ISSUE THREAD

**Issue by giannidhooge** [Cloudoki/Oauth2-stack#6]
Just tested the `dev-master` version together with Laravel 5.6 which gives some incompatibility issues.

This packages requires `laravelcollective/html: 5.2.*` which depends on `illuminate/view: 5.2.*`.
But Laravel 5.6 requires `illuminate/view: 5.6.*`, and therefore a composer installation error occurs: `Your requirements could not be resolved to an installable set of packages.`

Also, is it also possible to tag releases like you did before instead of forcing us to use `dev-master`?

**Comment by koenbetsens** [comment]
Latest release has correct reference to 5.6 dependencies.
Tag won't do, we'll need to test the stability a bit longer first.

**Comment by giannidhooge** [comment]
@koenbetsens On Laravel 5.1 we made use of these [traits](https://github.com/Cloudoki/Oauth2-stack/blob/lvl51/src/Cloudoki/OaStack/Traits/User.php). Those are only added on the `lvl51` branch. How can we migrate this for Laravel 5.6?

**Comment by koenbetsens** [comment]
Hi @giannidhooge, I could merge this with master and see what happens?

**Comment by giannidhooge** [comment]
Hi @koenbetsens! OK, let's find out!

**Comment by koenbetsens** [comment]
Added. If you have any bugs, please start a new ticket and I'll be happy to look into it.

**Comment by giannidhooge** [comment]
First tests are looking good. We will test further and let you know if any issue occurs. 

Thanks!
